export const comments = [
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '4.5',
    serviceRate: '4.5',
    facilityRate: '4.5',
    comment: '服务很好，工作人员态度热情。设施维护得也不错。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '4.5',
    serviceRate: '4.5',
    facilityRate: '4.5',
    comment: '服务很好，工作人员态度热情。设施维护得也不错。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '4.5',
    serviceRate: '4.5',
    facilityRate: '4.5',
    comment: '服务很好，工作人员态度热情。设施维护得也不错。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '4.5',
    serviceRate: '4.5',
    facilityRate: '4.5',
    comment: '服务很好，工作人员态度热情。设施维护得也不错。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '4.5',
    serviceRate: '4.5',
    facilityRate: '4.5',
    comment: '服务很好，工作人员态度热情。设施维护得也不错。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '4.5',
    serviceRate: '4.5',
    facilityRate: '4.5',
    comment: '服务很好，工作人员态度热情。设施维护得也不错。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '4.5',
    serviceRate: '4.5',
    facilityRate: '4.5',
    comment: '武侯祠真是个让人心灵沉静的好地方！一踏入红墙竹影，历史的厚重感便扑面而来。殿堂庄严肃穆，丞相的智慧与忠诚仿佛穿越千年，令人肃然起敬。园内绿树成荫，锦鲤悠然，漫步其中，既能凭吊先贤，又能享受片刻的宁静。这绝对是一次文化与美景交融的深度体验，值得细细品味，强烈推荐！',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.5',
    scenicRate: '2.5',
    serviceRate: '4.0',
    facilityRate: '3.0',
    comment: '历史氛围浓厚，但节假日人太多了，影响了游览体验。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.5',
    scenicRate: '5.0',
    serviceRate: '4.0',
    facilityRate: '4.5',
    comment: '景色很美，红墙竹影拍照特别出片。就是讲解器有点旧了。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.0',
    scenicRate: '2.0',
    serviceRate: '2.5',
    facilityRate: '1.5',
    comment: '商业化有点重，感觉失去了原本的宁静。不太推荐。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '5.0',
    serviceRate: '5.0',
    facilityRate: '5.0',
    comment: '完美！无论是历史价值还是景观维护都堪称一流，每次来都有新感悟。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.0',
    scenicRate: '3.5',
    serviceRate: '2.5',
    facilityRate: '3.0',
    comment: '中规中矩吧，名气很大，但实际感觉也就那样。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '4.5',
    serviceRate: '3.5',
    facilityRate: '4.0',
    comment: '值得一去，了解三国历史的好地方。建议请个导游，不然很多细节看不懂。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.5',
    scenicRate: '1.0',
    serviceRate: '2.0',
    facilityRate: '1.5',
    comment: '人挤人，体验感极差，再也不想节假日来了。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.5',
    scenicRate: '4.0',
    serviceRate: '4.5',
    facilityRate: '5.0',
    comment: '服务很好，工作人员态度热情。设施维护得也不错。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.5',
    scenicRate: '3.0',
    serviceRate: '2.0',
    facilityRate: '2.5',
    comment: '门票有点小贵，里面能逛的地方不算特别大。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '4.5',
    serviceRate: '5.0',
    facilityRate: '4.5',
    comment: '文化底蕴深厚，是成都的必游景点之一。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.5',
    scenicRate: '4.0',
    serviceRate: '3.0',
    facilityRate: '3.5',
    comment: '环境不错，就是指示牌不太清晰，差点迷路。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '3.5',
    serviceRate: '4.0',
    facilityRate: '4.0',
    comment: '整体感觉良好，对三国历史感兴趣的话会非常喜欢。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.0',
    scenicRate: '1.5',
    serviceRate: '1.0',
    facilityRate: '1.0',
    comment: '非常失望，和想象中差距太大，不推荐。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '5.0',
    serviceRate: '4.5',
    facilityRate: '5.0',
    comment: '一步一景，处处是故事。强烈建议历史爱好者前来。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.0',
    scenicRate: '2.5',
    serviceRate: '1.5',
    facilityRate: '2.0',
    comment: '管理有点混乱，卫生间也不太干净。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.5',
    scenicRate: '4.5',
    serviceRate: '4.5',
    facilityRate: '4.0',
    comment: '非常棒的体验，感受到了历史的庄严与美丽。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.0',
    scenicRate: '2.5',
    serviceRate: '3.5',
    facilityRate: '3.0',
    comment: '还行吧，顺路来看看可以，专程来没必要。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '4.0',
    serviceRate: '5.0',
    facilityRate: '4.5',
    comment: '服务态度一流，让人感觉很舒服。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.5',
    scenicRate: '1.0',
    serviceRate: '1.5',
    facilityRate: '2.0',
    comment: '设施陈旧，体验感一般。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '4.0',
    serviceRate: '4.0',
    facilityRate: '4.0',
    comment: '各方面都比较均衡，是一次不错的旅行。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.5',
    scenicRate: '3.0',
    serviceRate: '2.5',
    facilityRate: '2.0',
    comment: '有点小失望，可能期望太高了。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '5.0',
    serviceRate: '5.0',
    facilityRate: '5.0',
    comment: '无与伦比的历史文化体验，五星好评！',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.5',
    scenicRate: '3.0',
    serviceRate: '4.0',
    facilityRate: '3.5',
    comment: '服务比景色更让人印象深刻。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.5',
    scenicRate: '5.0',
    serviceRate: '4.0',
    facilityRate: '4.5',
    comment: '景色绝美，随便一拍都是大片。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.0',
    scenicRate: '1.0',
    serviceRate: '1.0',
    facilityRate: '1.0',
    comment: '完全不推荐，浪费时间和金钱。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '3.5',
    serviceRate: '4.5',
    facilityRate: '3.5',
    comment: '服务人员很专业，解答了很多问题。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.0',
    scenicRate: '2.0',
    serviceRate: '2.0',
    facilityRate: '2.5',
    comment: '整体感觉比较一般，没有太多亮点。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '4.5',
    serviceRate: '4.5',
    facilityRate: '5.0',
    comment: '设施维护得很好，干净整洁。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.0',
    scenicRate: '3.5',
    serviceRate: '3.0',
    facilityRate: '3.0',
    comment: '普普通通的一个景点，来过就好。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.5',
    scenicRate: '4.0',
    serviceRate: '5.0',
    facilityRate: '4.5',
    comment: '服务非常到位，让人宾至如归。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.5',
    scenicRate: '2.0',
    serviceRate: '1.0',
    facilityRate: '1.5',
    comment: '服务态度有待提高。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '4.5',
    serviceRate: '3.5',
    facilityRate: '4.0',
    comment: '景色很美，但服务还有提升空间。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.5',
    scenicRate: '2.0',
    serviceRate: '3.0',
    facilityRate: '2.5',
    comment: '景色一般，服务也一般。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '5.0',
    serviceRate: '4.5',
    facilityRate: '4.5',
    comment: '非常值得一游，历史感和美感兼具。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.5',
    scenicRate: '4.0',
    serviceRate: '3.0',
    facilityRate: '3.5',
    comment: '景色不错，但人太多了。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '3.0',
    serviceRate: '4.5',
    facilityRate: '4.0',
    comment: '服务是最大的亮点。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.0',
    scenicRate: '1.5',
    serviceRate: '1.5',
    facilityRate: '1.0',
    comment: '体验很差，不推荐。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '4.0',
    serviceRate: '5.0',
    facilityRate: '5.0',
    comment: '设施一流，服务一流！',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.0',
    scenicRate: '2.5',
    serviceRate: '2.0',
    facilityRate: '2.0',
    comment: '比较失望，不会再来了。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.5',
    scenicRate: '5.0',
    serviceRate: '4.5',
    facilityRate: '4.0',
    comment: '景色太美了，让人流连忘返。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.0',
    scenicRate: '3.0',
    serviceRate: '3.0',
    facilityRate: '3.0',
    comment: '中评，不好不坏。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '5.0',
    serviceRate: '5.0',
    facilityRate: '4.5',
    comment: '完美的历史之旅，强烈推荐！',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.5',
    scenicRate: '1.0',
    serviceRate: '2.0',
    facilityRate: '1.5',
    comment: '设施老旧，需要更新了。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '4.0',
    serviceRate: '4.0',
    facilityRate: '4.0',
    comment: '一次标准的景区游览体验。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.5',
    scenicRate: '3.0',
    serviceRate: '2.5',
    facilityRate: '3.0',
    comment: '设施比景色要好一些。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '4.5',
    serviceRate: '5.0',
    facilityRate: '5.0',
    comment: '无可挑剔，服务与设施都是顶级的。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.5',
    scenicRate: '3.5',
    serviceRate: '3.5',
    facilityRate: '3.5',
    comment: '各方面都还行，没有特别的惊喜。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.5',
    scenicRate: '4.0',
    serviceRate: '4.5',
    facilityRate: '5.0',
    comment: '设施非常完善，游玩很舒适。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.0',
    scenicRate: '1.0',
    serviceRate: '1.5',
    facilityRate: '1.0',
    comment: '非常不推荐，体验极差。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '4.5',
    serviceRate: '3.5',
    facilityRate: '4.0',
    comment: '景色和服务都还不错。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.0',
    scenicRate: '1.5',
    serviceRate: '2.5',
    facilityRate: '2.0',
    comment: '服务态度冷淡，体验不佳。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '5.0',
    serviceRate: '4.0',
    facilityRate: '5.0',
    comment: '景色和服务都达到了顶级水准。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.0',
    scenicRate: '3.5',
    serviceRate: '2.5',
    facilityRate: '3.0',
    comment: '景色尚可，但服务需要改进。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.5',
    scenicRate: '4.5',
    serviceRate: '5.0',
    facilityRate: '4.5',
    comment: '服务太棒了，必须点赞！',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.5',
    scenicRate: '2.0',
    serviceRate: '1.5',
    facilityRate: '1.5',
    comment: '各方面都比较差，不推荐。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '3.0',
    serviceRate: '4.0',
    facilityRate: '4.5',
    comment: '设施维护得不错，值得称赞。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.5',
    scenicRate: '2.5',
    serviceRate: '2.5',
    facilityRate: '2.5',
    comment: '各方面都很平庸。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '4.5',
    serviceRate: '4.5',
    facilityRate: '5.0',
    comment: '一次非常愉快的游览经历。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.5',
    scenicRate: '4.0',
    serviceRate: '3.5',
    facilityRate: '3.0',
    comment: '景色是最大的亮点。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '4.0',
    serviceRate: '4.5',
    facilityRate: '3.5',
    comment: '服务比预想的要好。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.0',
    scenicRate: '1.5',
    serviceRate: '1.0',
    facilityRate: '1.5',
    comment: '体验感很差，不会再来了。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '5.0',
    serviceRate: '5.0',
    facilityRate: '4.0',
    comment: '文化圣地，名不虚传！',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.0',
    scenicRate: '2.0',
    serviceRate: '2.5',
    facilityRate: '2.0',
    comment: '有点无聊，不太适合年轻人。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.5',
    scenicRate: '4.0',
    serviceRate: '4.0',
    facilityRate: '5.0',
    comment: '设施非常新，体验感很好。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.0',
    scenicRate: '3.0',
    serviceRate: '3.5',
    facilityRate: '3.0',
    comment: '还行吧，来都来了。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '4.5',
    serviceRate: '5.0',
    facilityRate: '4.5',
    comment: '服务热情周到，让人感觉很温暖。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.5',
    scenicRate: '1.0',
    serviceRate: '1.5',
    facilityRate: '2.0',
    comment: '管理混乱，体验感极差。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '4.5',
    serviceRate: '4.0',
    facilityRate: '3.5',
    comment: '景色很美，但设施有点旧。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.5',
    scenicRate: '3.0',
    serviceRate: '2.0',
    facilityRate: '2.5',
    comment: '服务是最大的短板。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '5.0',
    serviceRate: '4.5',
    facilityRate: '5.0',
    comment: '完美的景区，无可挑剔。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.5',
    scenicRate: '3.0',
    serviceRate: '3.5',
    facilityRate: '4.0',
    comment: '设施维护得不错，值得肯定。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.5',
    scenicRate: '5.0',
    serviceRate: '4.5',
    facilityRate: '4.0',
    comment: '景色太棒了，百看不厌。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.0',
    scenicRate: '1.0',
    serviceRate: '1.0',
    facilityRate: '1.5',
    comment: '非常不推荐，别来。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '3.5',
    serviceRate: '4.0',
    facilityRate: '4.0',
    comment: '一次中规中矩的游览。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.0',
    scenicRate: '2.5',
    serviceRate: '2.0',
    facilityRate: '2.5',
    comment: '整体感觉比较平淡。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '4.0',
    serviceRate: '5.0',
    facilityRate: '5.0',
    comment: '服务和设施都是顶级的，景色也很美。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.0',
    scenicRate: '3.5',
    serviceRate: '3.0',
    facilityRate: '3.0',
    comment: '景色还行，其他一般。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.5',
    scenicRate: '4.5',
    serviceRate: '4.0',
    facilityRate: '5.0',
    comment: '设施非常完善，游玩体验很棒。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.5',
    scenicRate: '2.0',
    serviceRate: '1.5',
    facilityRate: '1.0',
    comment: '体验感很差，不推荐。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '4.0',
    serviceRate: '4.5',
    facilityRate: '3.5',
    comment: '服务比景色更胜一筹。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.5',
    scenicRate: '2.0',
    serviceRate: '3.0',
    facilityRate: '2.5',
    comment: '景色一般，服务也一般。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '5.0',
    serviceRate: '5.0',
    facilityRate: '4.5',
    comment: '无与伦比的体验，强烈推荐！',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.5',
    scenicRate: '4.0',
    serviceRate: '3.0',
    facilityRate: '3.5',
    comment: '景色不错，但人太多了。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '3.0',
    serviceRate: '4.5',
    facilityRate: '4.0',
    comment: '服务是最大的亮点。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.0',
    scenicRate: '1.5',
    serviceRate: '1.5',
    facilityRate: '1.0',
    comment: '体验很差，不推荐。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '4.0',
    serviceRate: '5.0',
    facilityRate: '5.0',
    comment: '设施一流，服务一流！',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.0',
    scenicRate: '2.5',
    serviceRate: '2.0',
    facilityRate: '2.0',
    comment: '比较失望，不会再来了。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.5',
    scenicRate: '5.0',
    serviceRate: '4.5',
    facilityRate: '4.0',
    comment: '景色太美了，让人流连忘返。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.0',
    scenicRate: '3.0',
    serviceRate: '3.0',
    facilityRate: '3.0',
    comment: '中评，不好不坏。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '5.0',
    serviceRate: '5.0',
    facilityRate: '4.5',
    comment: '完美的历史之旅，强烈推荐！',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.5',
    scenicRate: '1.0',
    serviceRate: '2.0',
    facilityRate: '1.5',
    comment: '设施老旧，需要更新了。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '4.0',
    serviceRate: '4.0',
    facilityRate: '4.0',
    comment: '一次标准的景区游览体验。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.5',
    scenicRate: '3.0',
    serviceRate: '2.5',
    facilityRate: '3.0',
    comment: '设施比景色要好一些。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '4.5',
    serviceRate: '5.0',
    facilityRate: '5.0',
    comment: '无可挑剔，服务与设施都是顶级的。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.5',
    scenicRate: '3.5',
    serviceRate: '3.5',
    facilityRate: '3.5',
    comment: '各方面都还行，没有特别的惊喜。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.5',
    scenicRate: '4.0',
    serviceRate: '4.5',
    facilityRate: '5.0',
    comment: '设施非常完善，游玩很舒适。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.0',
    scenicRate: '1.0',
    serviceRate: '1.5',
    facilityRate: '1.0',
    comment: '非常不推荐，体验极差。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '4.5',
    serviceRate: '3.5',
    facilityRate: '4.0',
    comment: '景色和服务都还不错。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.0',
    scenicRate: '1.5',
    serviceRate: '2.5',
    facilityRate: '2.0',
    comment: '服务态度冷淡，体验不佳。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '5.0',
    serviceRate: '4.0',
    facilityRate: '5.0',
    comment: '景色和服务都达到了顶级水准。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.0',
    scenicRate: '3.5',
    serviceRate: '2.5',
    facilityRate: '3.0',
    comment: '景色尚可，但服务需要改进。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.5',
    scenicRate: '4.5',
    serviceRate: '5.0',
    facilityRate: '4.5',
    comment: '服务太棒了，必须点赞！',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.5',
    scenicRate: '2.0',
    serviceRate: '1.5',
    facilityRate: '1.5',
    comment: '各方面都比较差，不推荐。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '3.0',
    serviceRate: '4.0',
    facilityRate: '4.5',
    comment: '设施维护得不错，值得称赞。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.5',
    scenicRate: '2.5',
    serviceRate: '2.5',
    facilityRate: '2.5',
    comment: '各方面都很平庸。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '4.5',
    serviceRate: '4.5',
    facilityRate: '5.0',
    comment: '一次非常愉快的游览经历。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.5',
    scenicRate: '4.0',
    serviceRate: '3.5',
    facilityRate: '3.0',
    comment: '景色是最大的亮点。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '4.0',
    serviceRate: '4.5',
    facilityRate: '3.5',
    comment: '服务比预想的要好。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.0',
    scenicRate: '1.5',
    serviceRate: '1.0',
    facilityRate: '1.5',
    comment: '体验感很差，不会再来了。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '5.0',
    serviceRate: '5.0',
    facilityRate: '4.0',
    comment: '文化圣地，名不虚传！',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.0',
    scenicRate: '2.0',
    serviceRate: '2.5',
    facilityRate: '2.0',
    comment: '有点无聊，不太适合年轻人。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.5',
    scenicRate: '4.0',
    serviceRate: '4.0',
    facilityRate: '5.0',
    comment: '设施非常新，体验感很好。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.0',
    scenicRate: '3.0',
    serviceRate: '3.5',
    facilityRate: '3.0',
    comment: '还行吧，来都来了。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '4.5',
    serviceRate: '5.0',
    facilityRate: '4.5',
    comment: '服务热情周到，让人感觉很温暖。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.5',
    scenicRate: '1.0',
    serviceRate: '1.5',
    facilityRate: '2.0',
    comment: '管理混乱，体验感极差。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '4.5',
    serviceRate: '4.0',
    facilityRate: '3.5',
    comment: '景色很美，但设施有点旧。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.5',
    scenicRate: '3.0',
    serviceRate: '2.0',
    facilityRate: '2.5',
    comment: '服务是最大的短板。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '5.0',
    serviceRate: '4.5',
    facilityRate: '5.0',
    comment: '完美的景区，无可挑剔。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.5',
    scenicRate: '3.0',
    serviceRate: '3.5',
    facilityRate: '4.0',
    comment: '设施维护得不错，值得肯定。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.5',
    scenicRate: '5.0',
    serviceRate: '4.5',
    facilityRate: '4.0',
    comment: '景色太棒了，百看不厌。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.0',
    scenicRate: '1.0',
    serviceRate: '1.0',
    facilityRate: '1.5',
    comment: '非常不推荐，别来。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '3.5',
    serviceRate: '4.0',
    facilityRate: '4.0',
    comment: '一次中规中矩的游览。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.0',
    scenicRate: '2.5',
    serviceRate: '2.0',
    facilityRate: '2.5',
    comment: '整体感觉比较平淡。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '4.0',
    serviceRate: '5.0',
    facilityRate: '5.0',
    comment: '服务和设施都是顶级的，景色也很美。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.0',
    scenicRate: '3.5',
    serviceRate: '3.0',
    facilityRate: '3.0',
    comment: '景色还行，其他一般。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.5',
    scenicRate: '4.5',
    serviceRate: '4.0',
    facilityRate: '5.0',
    comment: '设施非常完善，游玩体验很棒。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.5',
    scenicRate: '2.0',
    serviceRate: '1.5',
    facilityRate: '1.0',
    comment: '体验感很差，不推荐。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '4.0',
    serviceRate: '4.5',
    facilityRate: '3.5',
    comment: '服务比景色更胜一筹。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.5',
    scenicRate: '2.0',
    serviceRate: '3.0',
    facilityRate: '2.5',
    comment: '景色一般，服务也一般。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '5.0',
    serviceRate: '5.0',
    facilityRate: '4.5',
    comment: '无与伦比的体验，强烈推荐！',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.5',
    scenicRate: '4.0',
    serviceRate: '3.0',
    facilityRate: '3.5',
    comment: '景色不错，但人太多了。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '3.0',
    serviceRate: '4.5',
    facilityRate: '4.0',
    comment: '服务是最大的亮点。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.0',
    scenicRate: '1.5',
    serviceRate: '1.5',
    facilityRate: '1.0',
    comment: '体验很差，不推荐。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '4.0',
    serviceRate: '5.0',
    facilityRate: '5.0',
    comment: '设施一流，服务一流！',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.0',
    scenicRate: '2.5',
    serviceRate: '2.0',
    facilityRate: '2.0',
    comment: '比较失望，不会再来了。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.5',
    scenicRate: '5.0',
    serviceRate: '4.5',
    facilityRate: '4.0',
    comment: '景色太美了，让人流连忘返。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.0',
    scenicRate: '3.0',
    serviceRate: '3.0',
    facilityRate: '3.0',
    comment: '中评，不好不坏。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '5.0',
    serviceRate: '5.0',
    facilityRate: '4.5',
    comment: '完美的历史之旅，强烈推荐！',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.5',
    scenicRate: '1.0',
    serviceRate: '2.0',
    facilityRate: '1.5',
    comment: '设施老旧，需要更新了。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '4.0',
    serviceRate: '4.0',
    facilityRate: '4.0',
    comment: '一次标准的景区游览体验。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.5',
    scenicRate: '3.0',
    serviceRate: '2.5',
    facilityRate: '3.0',
    comment: '设施比景色要好一些。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '4.5',
    serviceRate: '5.0',
    facilityRate: '5.0',
    comment: '无可挑剔，服务与设施都是顶级的。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.5',
    scenicRate: '3.5',
    serviceRate: '3.5',
    facilityRate: '3.5',
    comment: '各方面都还行，没有特别的惊喜。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.5',
    scenicRate: '4.0',
    serviceRate: '4.5',
    facilityRate: '5.0',
    comment: '设施非常完善，游玩很舒适。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.0',
    scenicRate: '1.0',
    serviceRate: '1.5',
    facilityRate: '1.0',
    comment: '非常不推荐，体验极差。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '4.5',
    serviceRate: '3.5',
    facilityRate: '4.0',
    comment: '景色和服务都还不错。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '2.0',
    scenicRate: '1.5',
    serviceRate: '2.5',
    facilityRate: '2.0',
    comment: '服务态度冷淡，体验不佳。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '5.0',
    scenicRate: '5.0',
    serviceRate: '4.0',
    facilityRate: '5.0',
    comment: '景色和服务都达到了顶级水准。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '3.0',
    scenicRate: '3.5',
    serviceRate: '2.5',
    facilityRate: '3.0',
    comment: '景色尚可，但服务需要改进。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.5',
    scenicRate: '4.5',
    serviceRate: '5.0',
    facilityRate: '4.5',
    comment: '服务太棒了，必须点赞！',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '1.5',
    scenicRate: '2.0',
    serviceRate: '1.5',
    facilityRate: '1.5',
    comment: '各方面都比较差，不推荐。',
  },
  {
    name: '武侯祠',
    provinceName: '四川省',
    recommendRate: '4.0',
    scenicRate: '3.0',
    serviceRate: '4.0',
    facilityRate: '4.5',
    comment: '设施维护得不错，值得称赞。',
  },
]